### ISSUE TITLE
Handle new query types once core #297 is merged

### ISSUE THREAD

**Issue by bserdar** [lightblue-platform/lightblue-ldap#40]
Once https://github.com/lightblue-platform/lightblue-core/pull/297 is merged, the back-end code should handle the new query types: NaryValueRelationalExpression and NaryFieldRelationalExpression instead of NaryRelationalExpression. One way to make sure the code remains aware of the changes is to make sure you use QueryIterator when processing queries, instead of manually descending the query tree.

**Comment by bserdar** [comment]
Rewrite FilterTranslator to use QueryIterator.

**Comment by dcrissman** [comment]
Spent some time looking at this today and I am not sure if the QueryIterator model, as it is, will work for the purposes of creating a Filter. Maybe if we could find some meaningful way to refactor QueryIterator, because I do like the idea of the core framework owning the driving mechanism.

Unlike QueryExpression#BindItr there is not a single top level container that the Filters can be added to. Filter is a composite which for more complex operations like AND or OR, require a special factory method to be used to connect them, where you pass in other Filters like branches and leafs in a tree structure.

**Comment by bserdar** [comment]
The query tree structure doesn't have a single top level container either.
Query expressions form a tree, and QueryIterator recursively descends into
that tree. So, based on your description, QueryIterator is the perfect
device to deal with those kinds of queries.

These structures are called "abstract syntax trees" by the way.

**Comment by dcrissman** [comment]
What I meant earlier is that Filter is a tree structure also. QueryIterator walks the query tree, but the methods only support returning QueryExpression instances. What if there was a generic version of QueryIterator that could return something other than just QueryExpression?

**Comment by bserdar** [comment]
Return 'this'. Keep an instance of filter in your implementation of
QueryIterator, and build that.

**Comment by dcrissman** [comment]
Are you suggesting that each method set a new Field instance to the internal class level variable, with calling methods using any existing Field to create a new Field? I think that would lead to difficult to follow logic.

**Comment by bserdar** [comment]
I see your point. Let me think about changing the query iterator a bit. I
think I can make a more abstract version of QueryIterator that either
returns a generic type, or one that works with closures, and re-implement
the existing query iterator as an extension of that.

**Comment by bserdar** [comment]
See if this helps:

https://github.com/bserdar/lightblue-core/commit/99b2b3183b1441281bed5d966f57b93ac69f0e05

**Comment by dcrissman** [comment]
Yes, I believe that will work.
