### ISSUE TITLE
Broken from upstream changes

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-ldap#89]
See https://github.com/lightblue-platform/lightblue-core/pull/624

Compilation issues need to be resolved.

**Comment by dcrissman** [comment]
@bserdar - [LdapPropertyParser](https://github.com/lightblue-platform/lightblue-ldap/blob/master/lightblue-ldap-metadata/src/main/java/com/redhat/lightblue/metadata/ldap/parser/LdapPropertyParser.java) needs to be updated per the PR in the description of this ticket. It looks like the two methods implemented, no longer exist on the parent class. Could you point me at an example or tell me what changes need to be made to fix this? Thanks.

**Comment by bserdar** [comment]
Instead of parse(...), you need to write:

Object parseProperty(MetadataParser<T> p,T container, String name) where:
   p: the parser parsing it
   container: The object containing the property,
   name: The name of the property

The expectation is that you parse container.name, and return it as an
object.

Also, you need convertProperty(MetadataParser<T> parser,
                                                  T container,
                                                   String propertyName,
                                                   Object propertyValue)

  where
   p: the parser
   container: The object containing the property
   propertyName: name of the property
   propertyValue: The value of the property, whatever was returned by
parseProperty

In this specific case, parseProperty will parse and return an instance of
LdapMetadata, and convertProperty will get that LdapMetadata instrance as
propertyValue.
